// figma node: 761:11213 Badge (600 variants)
const __variants = {
  "mode=light|size=md|variant=solid|color=primary|shape=round-square": {
    height: 28,
    borderRadius: 4,
    gap: 4,
    padding: "0px 10px 0px 10px",
  },
  "mode=light|size=lg|variant=solid|color=primary|shape=round-square": {
    height: 32,
    borderRadius: 4,
    gap: 6,
    padding: "0px 12px 0px 12px",
  },
  "mode=light|size=md|variant=solid|color=success|shape=round-square": {
    height: 28,
    borderRadius: 4,
    backgroundColor: "var(--color-surface-success)",
    gap: 4,
    padding: "0px 10px 0px 10px",
  },
  "mode=light|size=lg|variant=solid|color=success|shape=round-square": {
    height: 32,
    borderRadius: 4,
    backgroundColor: "var(--color-surface-success)",
    gap: 6,
    padding: "0px 12px 0px 12px",
  },
  "mode=light|size=xl|variant=solid|color=success|shape=round-square": { backgroundColor: "var(--color-surface-success)" },
  "mode=light|size=md|variant=solid|color=error|shape=round-square": {
    height: 28,
    borderRadius: 4,
    backgroundColor: "var(--color-surface-error)",
    gap: 4,
    padding: "0px 10px 0px 10px",
  },
  "mode=light|size=lg|variant=solid|color=error|shape=round-square": {
    height: 32,
    borderRadius: 4,
    backgroundColor: "var(--color-surface-error)",
    gap: 6,
    padding: "0px 12px 0px 12px",
  },
  "mode=light|size=xl|variant=solid|color=error|shape=round-square": { backgroundColor: "var(--color-surface-error)" },
  "mode=light|size=md|variant=solid|color=secondary|shape=round-square": {
    height: 28,
    borderRadius: 4,
    backgroundColor: "var(--color-surface-warning)",
    gap: 4,
    padding: "0px 10px 0px 10px",
  },
  "mode=light|size=lg|variant=solid|color=secondary|shape=round-square": {
    height: 32,
    borderRadius: 4,
    backgroundColor: "var(--color-surface-warning)",
    gap: 6,
    padding: "0px 12px 0px 12px",
  },
  "mode=light|size=xl|variant=solid|color=secondary|shape=round-square": { backgroundColor: "var(--color-surface-warning)" },
  "mode=light|size=md|variant=solid|color=warning|shape=round-square": {
    height: 28,
    borderRadius: 4,
    backgroundColor: "var(--color-surface-light-warning)",
    gap: 4,
    padding: "0px 10px 0px 10px",
  },
  "mode=light|size=lg|variant=solid|color=warning|shape=round-square": {
    height: 32,
    borderRadius: 4,
    backgroundColor: "var(--color-surface-light-warning)",
    gap: 6,
    padding: "0px 12px 0px 12px",
  },
  "mode=light|size=xl|variant=solid|color=warning|shape=round-square": { backgroundColor: "var(--color-surface-light-warning)" },
  "mode=light|size=md|variant=solid|color=grayscale|shape=round-square": {
    height: 28,
    borderRadius: 4,
    backgroundColor: "var(--color-surface-gray)",
    gap: 4,
    padding: "0px 10px 0px 10px",
  },
  "mode=light|size=lg|variant=solid|color=grayscale|shape=round-square": {
    height: 32,
    borderRadius: 4,
    backgroundColor: "var(--color-surface-gray)",
    gap: 6,
    padding: "0px 12px 0px 12px",
  },
  "mode=light|size=xl|variant=solid|color=grayscale|shape=round-square": { backgroundColor: "var(--color-surface-gray)" },
  "mode=light|size=md|variant=solid-pastel|color=primary|shape=round-square": {
    height: 28,
    borderRadius: 4,
    backgroundColor: "var(--color-surface-brand-subtle)",
    gap: 4,
    padding: "0px 8px 0px 8px",
  },
  "mode=light|size=lg|variant=solid-pastel|color=primary|shape=round-square": {
    height: 32,
    borderRadius: 4,
    backgroundColor: "var(--color-surface-brand-subtle)",
    gap: 4,
    padding: "0px 12px 0px 12px",
  },
  "mode=light|size=xl|variant=solid-pastel|color=primary|shape=round-square": { backgroundColor: "var(--color-surface-brand-subtle)" },
  "mode=light|size=md|variant=solid-pastel|color=success|shape=round-square": {
    height: 28,
    borderRadius: 4,
    backgroundColor: "var(--color-surface-success-subtle)",
    gap: 4,
    padding: "0px 8px 0px 8px",
  },
  "mode=light|size=lg|variant=solid-pastel|color=success|shape=round-square": {
    height: 32,
    borderRadius: 4,
    backgroundColor: "var(--color-surface-success-subtle)",
    gap: 4,
    padding: "0px 12px 0px 12px",
  },
  "mode=light|size=xl|variant=solid-pastel|color=success|shape=round-square": { backgroundColor: "var(--color-surface-success-subtle)" },
  "mode=light|size=md|variant=solid-pastel|color=error|shape=round-square": {
    height: 28,
    borderRadius: 4,
    backgroundColor: "var(--color-surface-error-subtle)",
    gap: 4,
    padding: "0px 8px 0px 8px",
  },
  "mode=light|size=lg|variant=solid-pastel|color=error|shape=round-square": {
    height: 32,
    borderRadius: 4,
    backgroundColor: "var(--color-surface-error-subtle)",
    gap: 4,
    padding: "0px 12px 0px 12px",
  },
  "mode=light|size=xl|variant=solid-pastel|color=error|shape=round-square": { backgroundColor: "var(--color-surface-error-subtle)" },
  "mode=light|size=md|variant=solid-pastel|color=secondary|shape=round-square": {
    height: 28,
    borderRadius: 4,
    backgroundColor: "var(--color-surface-warning-subtle)",
    gap: 4,
    padding: "0px 8px 0px 8px",
  },
  "mode=light|size=lg|variant=solid-pastel|color=secondary|shape=round-square": {
    height: 32,
    borderRadius: 4,
    backgroundColor: "var(--color-surface-warning-subtle)",
    gap: 4,
    padding: "0px 12px 0px 12px",
  },
  "mode=light|size=xl|variant=solid-pastel|color=secondary|shape=round-square": { backgroundColor: "var(--color-surface-warning-subtle)" },
  "mode=light|size=md|variant=solid-pastel|color=warning|shape=round-square": {
    height: 28,
    borderRadius: 4,
    backgroundColor: "var(--color-surface-light-warning-subtle)",
    gap: 4,
    padding: "0px 8px 0px 8px",
  },
  "mode=light|size=lg|variant=solid-pastel|color=warning|shape=round-square": {
    height: 32,
    borderRadius: 4,
    backgroundColor: "var(--color-surface-light-warning-subtle)",
    gap: 4,
    padding: "0px 12px 0px 12px",
  },
  "mode=light|size=xl|variant=solid-pastel|color=warning|shape=round-square": { backgroundColor: "var(--color-surface-light-warning-subtle)" },
  "mode=light|size=md|variant=solid-pastel|color=grayscale|shape=round-square": {
    height: 28,
    borderRadius: 4,
    backgroundColor: "var(--color-surface-gray-subtle)",
    gap: 4,
    padding: "0px 8px 0px 8px",
  },
  "mode=light|size=lg|variant=solid-pastel|color=grayscale|shape=round-square": {
    height: 32,
    borderRadius: 4,
    backgroundColor: "var(--color-surface-gray-subtle)",
    gap: 4,
    padding: "0px 12px 0px 12px",
  },
  "mode=light|size=xl|variant=solid-pastel|color=grayscale|shape=round-square": { backgroundColor: "var(--color-surface-gray-subtle)" },
  "mode=light|size=md|variant=outline|color=primary|shape=round-square": {
    height: 28,
    borderRadius: 4,
    backgroundColor: "revert",
    gap: 4,
    padding: "0px 8px 0px 8px",
    boxShadow: "inset 0 0 0 1px var(--color-border-brand)",
  },
  "mode=light|size=md|variant=dot-accent|color=primary|shape=round-square": {
    height: 28,
    borderRadius: 4,
    backgroundColor: "revert",
    gap: 4,
    padding: "0px 8px 0px 8px",
  },
  "mode=light|size=md|variant=dot-neutral|color=primary|shape=round-square": {
    height: 28,
    borderRadius: 4,
    backgroundColor: "revert",
    gap: 4,
    padding: "0px 8px 0px 8px",
  },
  "mode=light|size=lg|variant=outline|color=primary|shape=round-square": {
    height: 32,
    borderRadius: 4,
    backgroundColor: "revert",
    gap: 4,
    padding: "0px 12px 0px 12px",
    boxShadow: "inset 0 0 0 1px var(--color-border-brand)",
  },
  "mode=light|size=lg|variant=dot-accent|color=primary|shape=round-square": {
    height: 32,
    borderRadius: 4,
    backgroundColor: "revert",
    gap: 4,
    padding: "0px 12px 0px 12px",
  },
  "mode=light|size=lg|variant=dot-neutral|color=primary|shape=round-square": {
    height: 32,
    borderRadius: 4,
    backgroundColor: "revert",
    gap: 4,
    padding: "0px 12px 0px 12px",
  },
  "mode=light|size=xl|variant=outline|color=primary|shape=round-square": { backgroundColor: "revert", boxShadow: "inset 0 0 0 1px var(--color-border-brand)" },
  "mode=light|size=xl|variant=dot-accent|color=primary|shape=round-square": { backgroundColor: "revert" },
  "mode=light|size=xl|variant=dot-neutral|color=primary|shape=round-square": { backgroundColor: "revert" },
  "mode=light|size=md|variant=outline|color=success|shape=round-square": {
    height: 28,
    borderRadius: 4,
    backgroundColor: "revert",
    gap: 4,
    padding: "0px 8px 0px 8px",
    boxShadow: "inset 0 0 0 1px var(--color-border-success)",
  },
  "mode=light|size=md|variant=dot-accent|color=success|shape=round-square": {
    height: 28,
    borderRadius: 4,
    backgroundColor: "revert",
    gap: 4,
    padding: "0px 8px 0px 8px",
  },
  "mode=light|size=md|variant=dot-neutral|color=success|shape=round-square": {
    height: 28,
    borderRadius: 4,
    backgroundColor: "revert",
    gap: 4,
    padding: "0px 8px 0px 8px",
  },
  "mode=light|size=lg|variant=outline|color=success|shape=round-square": {
    height: 32,
    borderRadius: 4,
    backgroundColor: "revert",
    gap: 4,
    padding: "0px 12px 0px 12px",
    boxShadow: "inset 0 0 0 1px var(--color-border-success)",
  },
  "mode=light|size=lg|variant=dot-accent|color=success|shape=round-square": {
    height: 32,
    borderRadius: 4,
    backgroundColor: "revert",
    gap: 4,
    padding: "0px 12px 0px 12px",
  },
  "mode=light|size=lg|variant=dot-neutral|color=success|shape=round-square": {
    height: 32,
    borderRadius: 4,
    backgroundColor: "revert",
    gap: 4,
    padding: "0px 12px 0px 12px",
  },
  "mode=light|size=xl|variant=outline|color=success|shape=round-square": { backgroundColor: "revert", boxShadow: "inset 0 0 0 1px var(--color-border-success)" },
  "mode=light|size=xl|variant=dot-accent|color=success|shape=round-square": { backgroundColor: "revert" },
  "mode=light|size=xl|variant=dot-neutral|color=success|shape=round-square": { backgroundColor: "revert" },
  "mode=light|size=md|variant=outline|color=error|shape=round-square": {
    height: 28,
    borderRadius: 4,
    backgroundColor: "revert",
    gap: 4,
    padding: "0px 8px 0px 8px",
    boxShadow: "inset 0 0 0 1px var(--color-border-error)",
  },
  "mode=light|size=md|variant=dot-accent|color=error|shape=round-square": {
    height: 28,
    borderRadius: 4,
    backgroundColor: "revert",
    gap: 4,
    padding: "0px 8px 0px 8px",
  },
  "mode=light|size=md|variant=dot-neutral|color=error|shape=round-square": {
    height: 28,
    borderRadius: 4,
    backgroundColor: "revert",
    gap: 4,
    padding: "0px 8px 0px 8px",
  },
  "mode=light|size=lg|variant=outline|color=error|shape=round-square": {
    height: 32,
    borderRadius: 4,
    backgroundColor: "revert",
    gap: 4,
    padding: "0px 12px 0px 12px",
    boxShadow: "inset 0 0 0 1px var(--color-border-error)",
  },
  "mode=light|size=lg|variant=dot-accent|color=error|shape=round-square": {
    height: 32,
    borderRadius: 4,
    backgroundColor: "revert",
    gap: 4,
    padding: "0px 12px 0px 12px",
  },
  "mode=light|size=lg|variant=dot-neutral|color=error|shape=round-square": {
    height: 32,
    borderRadius: 4,
    backgroundColor: "revert",
    gap: 4,
    padding: "0px 12px 0px 12px",
  },
  "mode=light|size=xl|variant=outline|color=error|shape=round-square": { backgroundColor: "revert", boxShadow: "inset 0 0 0 1px var(--color-border-error)" },
  "mode=light|size=xl|variant=dot-accent|color=error|shape=round-square": { backgroundColor: "revert" },
  "mode=light|size=xl|variant=dot-neutral|color=error|shape=round-square": { backgroundColor: "revert" },
  "mode=light|size=md|variant=outline|color=secondary|shape=round-square": {
    height: 28,
    borderRadius: 4,
    backgroundColor: "revert",
    gap: 4,
    padding: "0px 8px 0px 8px",
    boxShadow: "inset 0 0 0 1px var(--color-border-warning)",
  },
  // …+535 more variants not captured: "mode=light|size=md|variant=dot-accent|color=secondary|shape=round-square", "mode=light|size=md|variant=dot-neutral|color=secondary|shape=round-square", "mode=light|size=lg|variant=outline|color=secondary|shape=round-square", "mode=light|size=lg|variant=dot-accent|color=secondary|shape=round-square", "mode=light|size=lg|variant=dot-neutral|color=secondary|shape=round-square", "mode=light|size=xl|variant=outline|color=secondary|shape=round-square", "mode=light|size=xl|variant=dot-accent|color=secondary|shape=round-square", "mode=light|size=xl|variant=dot-neutral|color=secondary|shape=round-square", "mode=light|size=md|variant=outline|color=warning|shape=round-square", "mode=light|size=md|variant=dot-accent|color=warning|shape=round-square", …
};
const __venc = (v) => String(v).replace(/[%|=]/g, encodeURIComponent);
const __vkey = (p) => "mode=" + __venc(p.mode) + '|' + "size=" + __venc(p.size) + '|' + "variant=" + __venc(p.variant) + '|' + "color=" + __venc(p.color) + '|' + "shape=" + __venc(p.shape);

export function Badge(_p = {}) {
  const props = { ..._p, label: _p.label ?? "레이블", leftIcon: _p.leftIcon ?? true, mode: _p.mode ?? "dark", size: _p.size ?? "xl", variant: _p.variant ?? "solid", color: _p.color ?? "primary", shape: _p.shape ?? "round-square" };
  const __vs = __variants[__vkey(props)] ?? {};
  return (
    <div className={props.className} style={{
      width: "fit-content",
      height: 36,
      borderRadius: 6,
      backgroundColor: "var(--color-surface-brand)",
      display: "flex",
      flexDirection: "row",
      gap: 8,
      padding: "0px 14px 0px 14px",
      justifyContent: "center",
      alignItems: "center",
      flexWrap: "nowrap",
      boxSizing: "border-box",
      position: "relative",
      ...__vs, ...props.style,
    }}>
      {props.leftIcon && (
      <div style={{
        position: "relative",
        width: "calc(var(--sizing-icon-lg) * 1px)",
        height: 20,
        display: "flex",
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        flexWrap: "nowrap",
        flexShrink: 0,
      }}>
        <div style={{
          position: "relative",
          width: 20,
          flexShrink: 0,
          alignSelf: "stretch",
        }}>
          <svg width={15.238} height={16.667} viewBox="0 0 15.238 16.667" fill="none" style={{
            position: "absolute",
            left: 2.381,
            top: 1.667,
            width: 15.238,
            height: 16.667,
            color: "rgb(255,255,255)",
          }}>
            <path d={"M 1.905 14.762 L 4.762 14.762 L 4.762 9.048 L 10.476 9.048 L 10.476 14.762 L 13.333 14.762 L 13.333 6.19 L 7.619 1.905 L 1.905 6.19 L 1.905 14.762 Z M 1.905 16.667 C 1.381 16.667 0.933 16.48 0.56 16.108 C 0.187 15.734 0 15.286 0 14.762 L 0 6.19 C 0 5.889 0.068 5.603 0.203 5.333 C 0.337 5.063 0.524 4.841 0.762 4.667 L 6.476 0.381 C 6.651 0.254 6.833 0.159 7.024 0.095 C 7.214 0.032 7.413 0 7.619 0 C 7.825 0 8.024 0.032 8.214 0.095 C 8.405 0.159 8.587 0.254 8.762 0.381 L 14.476 4.667 C 14.714 4.841 14.901 5.063 15.036 5.333 C 15.171 5.603 15.238 5.889 15.238 6.19 L 15.238 14.762 C 15.238 15.286 15.052 15.734 14.679 16.108 C 14.306 16.48 13.857 16.667 13.333 16.667 L 8.571 16.667 L 8.571 10.952 L 6.667 10.952 L 6.667 16.667 L 1.905 16.667 Z"} fill="currentColor" fillRule="nonzero" />
          </svg>
        </div>
      </div>
      )}
      <span style={{
        position: "relative",
        fontFamily: "\"Spoqa Han Sans Neo\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif",
        fontWeight: 400,
        fontSize: 14,
        textAlign: "center",
        whiteSpace: "nowrap",
        lineHeight: 1.399999976158142,
        letterSpacing: "-0.030em",
        color: "var(--color-text-on-brand)",
        flexShrink: 0,
      }}>{props.label}</span>
    </div>
  );
}
export default Badge;
